{{- if .Values.blueGreen.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "springboot-app.fullname" . }}-preview
  labels:
    {{- include "springboot-app.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "springboot-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    version-color: {{ .Values.blueGreen.previewColor }}
{{- end }}