image:
  repository: 776751404462.dkr.ecr.ap-south-1.amazonaws.com/springboot-devops-app
  tag: "21"

service:
  port: 80
  targetPort: 8080

blueGreen:
  enabled: true
  activeColor: blue
  previewColor: green

colors:
  blue:
    enabled: true
    replicaCount: 1
    imageTag: "21"
  green:
    enabled: true
    replicaCount: 1
    imageTag: "21"