replicaCount: 1

image:776751404462.dkr.ecr.ap-south-1.amazonaws.com/springboot-devops-app
  tag: latest, 12

service:
  type: ClusterIP

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

hpa:
  enabled: false

pdb:
  enabled: false