replicaCount: 2

image:
  repository: 776751404462.dkr.ecr.ap-south-1.amazonaws.com/springboot-devops-app
  tag: "21"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

hpa:
  enabled: false
 
pdb:
  enabled: false
 