replicaCount: 2

image:
  tag: "prod-latest"

service:
  type: LoadBalancer

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  averageUtilization: 70

pdb:
  enabled: true
  minAvailable: 1