apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: springboot-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yalamuri-babu/springboot-platform-demo.git
    targetRevision: main
    path: helm/springboot-app
    helm:
      valueFiles:
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
